default_roles:
# #  - bat
#  # - docker # munnual brew install docker
  - eza
# #  - fonts
  - fzf
  - gh
  - go
  - helm
# #  - karabiner
  - k8s
  - k9s
  - lazydocker
  - lazygit
  - lua
  - neovim
 # - nordvpn
  - nvm
  - npm
  - obsidian
  - opencode
  - python
  - raycast
  - rust
  - spotify
  - system
  - terraform
  - tmux
  - wezterm
  - zoxide
  - zsh
  - yazi
k8s:
  repo:
    version: "v1.29"
helm:
  repos:
    - name: traefik
      url: https://helm.traefik.io/traefik
