- name: "Rust | Install Rustup"
  ansible.builtin.shell:
    cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
  environment:
    CARGO_HOME: "{{ ansible_env.HOME }}/.cargo"
    RUSTUP_HOME: "{{ ansible_env.HOME }}/.rustup"
    HOME: "{{ ansible_env.HOME }}"
- name: "Rust | Install Rust components"
  ansible.builtin.shell: >
    bash -l -c "source \"$HOME/.cargo/env\" && rustup component add {{ item }}"
  loop:
    - rustfmt
    - clippy
  environment:
    HOME: "{{ ansible_env.HOME }}"
- name: "Rust | Update Rust toolchain"
  ansible.builtin.shell: >
    bash -l -c "source \"$HOME/.cargo/env\" && rustup update"
  environment:
    HOME: "{{ ansible_env.HOME }}"

