- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config
- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists
- name: "{{ role_name }} | Copy yazi Configuration"
  ansible.builtin.copy:
    src: "yazi"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: '0644'
    directory_mode: "0755"
    force: true
- name: "Yazi | Check if flavor already exists"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/yazi/flavors/catppuccin-mocha.yazi/flavor.toml"
  register: yazi_flavor_check
- name: "Yazi | Install Catppuccin flavor via ya pkg"
  ansible.builtin.command:
    cmd: ya pkg add yazi-rs/flavors:catppuccin-mocha
  when: not yazi_flavor_check.stat.exists
- name: "Yazi | Verify installation"
  ansible.builtin.command:
    cmd: yazi --version
  register: yazi_version
  changed_when: false
- name: "Yazi | Show Yazi version"
  ansible.builtin.debug:
    var: yazi_version.stdout
