- name: "System | MacOSX | Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
- name: "System | MacOSX | Install Homebrew Packages"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - jq
    - tree
    - ripgrep


    brew install yazi ffmpeg sevenzip jq poppler fd ripgrep fzf zoxide resvg imagemagick font-symbols-only-nerd-font
