- name: "Cleanup lazydocker downloaded tar"
  ansible.builtin.file:
    path: "/tmp/{{ lazydocker_file }}.tar.gz"
    state: absent
  become: true
- name: "Remove extracted lazydocker directory"
  ansible.builtin.file:
    path: "/tmp/lazydocker"
    state: absent
  become: true
