- name: "Zsh | MacOSX | Install"
  community.general.homebrew:
    name: zsh
    state: present
- name: "Zinit | MacOSX | Install"
  community.general.homebrew:
    name: zinit
    state: present
- name: "Zsh | MacOSX | Get current shell"
  ansible.builtin.command: dscl . -read /Users/{{ ansible_env.USER }} UserShell
  register: current_shell
  changed_when: false
