- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config
- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists
- name: "{{ role_name }} | Copy .wezterm.lua Configuration"
  ansible.builtin.copy:
    src: ".wezterm.lua"
    dest: "{{ ansible_user_dir }}/.wezterm.lua"
    mode: '0644'
    owner: "{{ ansible_env.USER }}" # Garantir que o arquivo seja do usuário correto
    group: "{{ ansible_env.USER }}"
