- name: "Bat | MacOSX | Install bat"
  community.general.homebrew:
    name: bat
    state: present

- name: "Bat | MacOSX | Ensure bat themes directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/bat/themes"
    state: directory
    mode: "0755"

- name: "Bat | MacOSX | Copy bat config file"
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_user_dir }}/.config/bat/config"
    mode: "0644"
    force: true 
  notify: Rebuild bat cache

- name: "Bat | MacOSX | Download Catppuccin Mocha theme if missing"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
    dest: "{{ ansible_user_dir }}/.config/bat/themes/Catppuccin-Mocha.tmTheme"
    mode: "0644"
    force: false
  notify: Rebuild bat cache

# - name: "Bat | MacOSX | Install bat"
#   community.general.homebrew:
#     name: bat
#     state: present
# # wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme
# - name: "Bat | MacOSX | Create bat themes directory"
#   ansible.builtin.file:
#     path: "{{ lookup('env', 'HOME') }}/.config/bat/themes"
#     state: directory
#     mode: "0755"
# - name: "Bat | MacOSX | Install bat config"
#   ansible.builtin.copy:
#     src: config
#     dest: "{{ lookup('env', 'HOME') }}/.config/bat/config"
#     mode: "0644"
# - name: "Bat | MacOSX | Install bat themes"
#   ansible.builtin.get_url:
#     url: "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
#     dest: "{{ lookup('env', 'HOME') }}/.config/bat/themes/Catppuccin Mocha.tmTheme"
#     mode: "0644"
